// Generated by mkdbuild_profiler - Level 1
// Timestamp: 1767531948

#[cfg(feature = "profiling")]
use std::time::Instant;

fn main() {
    println!("Level 1 Compiler with Profiling");
    let start = Instant::now();
    
    let programs = vec!["const x = 1;", "const y = true;"];
    for program in programs {
        println!("Compiling: {}", program);
    }
    
    println!("Execution time: {:?}", start.elapsed());
}
