// NOTE: The `supported_targets!` macro should be the only content in this file.
// This is to avoid circular dependencies with `mod.rs`.

// NOTE: This file is generated by a script. Do not modify it manually.
// Instead, modify the script that generates it.
//
// The script is located at `scripts/generate_supported_targets.sh`
//
// To regenerate this file, run:
// `scripts/generate_supported_targets.sh > submodules/rust/compiler/rustc_target/src/spec/supported_targets.rs`
//
// And remember to format the file after regeneration:
// `rustfmt submodules/rust/compiler/rustc_target/src/spec/supported_targets.rs`
//
// Once the `supported_targets!` macro is no longer needed, this file can be removed.
// We are moving towards a system where targets are loaded dynamically from `target.json` files.

use super::{base, apple};
use crate::spec::Target;
macro_rules! supported_targets {
    ({
        $( ($triple:tt, $arch:expr, $os:expr) => $target:expr ),* $(,)*
    }) => {
        pub const ALL_TARGETS: &[(&str, &str, &str, &Target)] = &[
            $(
                ($triple, $arch, $os, $target),
            )*
        ];
    };
}

supported_targets! {
    {
        // ("aarch64-apple-darwin", "aarch64", "darwin") => &apple::TARGET_AARCH64_APPLE_DARWIN,
        // ("aarch64-apple-ios", "aarch64", "ios") => &apple::TARGET_AARCH64_APPLE_IOS,
        // ("aarch64-apple-ios-macabi", "aarch64", "ios") => &apple::TARGET_AARCH64_APPLE_IOS_MACABI,
        // ("aarch64-apple-ios-sim", "aarch64", "ios") => &apple::TARGET_AARCH64_APPLE_IOS_SIM,
        // ("aarch64-fuchsia", "aarch64", "fuchsia") => &base::TARGET_AARCH64_FUCHSIA,
        // ("aarch64-linux-android", "aarch64", "android") => &base::TARGET_AARCH64_LINUX_ANDROID,
        // ("aarch64-linux-ohos", "aarch64", "ohos") => &base::TARGET_AARCH64_LINUX_OHOS,
        // ("aarch64-unknown-linux-gnu", "aarch64", "linux") => &base::TARGET_AARCH64_UNKNOWN_LINUX_GNU,
        // ("aarch64-unknown-linux-musl", "aarch64", "linux") => &base::TARGET_AARCH64_UNKNOWN_LINUX_MUSL,
        // ("aarch64-unknown-nto-qnx700", "aarch64", "nto") => &base::TARGET_AARCH64_UNKNOWN_NTO_QNX700,
        // ("aarch64-unknown-nto-qnx710", "aarch64", "nto") => &base::TARGET_AARCH64_UNKNOWN_NTO_QNX710,
        // ("aarch64-unknown-redox", "aarch64", "redox") => &base::TARGET_AARCH64_UNKNOWN_REDOX,
        // ("arm-none-eabi", "arm", "none") => &base::TARGET_ARM_NONE_EABI,
        // ("armv7-linux-androideabi", "arm", "android") => &base::TARGET_ARMV7_LINUX_ANDROIDEABI,
        // ("armv7-unknown-linux-gnueabi", "arm", "linux") => &base::TARGET_ARMV7_UNKNOWN_LINUX_GNUEABI,
        // ("armv7-unknown-linux-gnueabihf", "arm", "linux") => &base::TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF,
        // ("armv7-unknown-linux-musleabi", "arm", "linux") => &base::TARGET_ARMV7_UNKNOWN_LINUX_MUSLEABI,
        // ("armv7-unknown-linux-musleabihf", "arm", "linux") => &base::TARGET_ARMV7_UNKNOWN_LINUX_MUSLEABIHF,
        // ("armv7r-none-eabi", "arm", "none") => &base::TARGET_ARMV7R_NONE_EABI,
        // ("armv7r-none-eabihf", "arm", "none") => &base::TARGET_ARMV7R_NONE_EABIHF,
        // ("asmjs-unknown-emscripten", "asmjs", "emscripten") => &base::TARGET_ASMJS_UNKNOWN_EMSCRIPTEN,
        // ("avr-unknown-unknown", "avr", "unknown") => &base::TARGET_AVR_UNKNOWN_UNKNOWN,
        // ("i586-pc-windows-msvc", "x86", "windows") => &base::TARGET_I586_PC_WINDOWS_MSVC,
        // ("i686-apple-darwin", "x86", "darwin") => &apple::TARGET_I686_APPLE_DARWIN,
        // ("i686-linux-android", "x86", "android") => &base::TARGET_I686_LINUX_ANDROID,
        // ("i686-pc-windows-gnu", "x86", "windows") => &base::TARGET_I686_PC_WINDOWS_GNU,
        // ("i686-pc-windows-msvc", "x86", "windows") => &base::TARGET_I686_PC_WINDOWS_MSVC,
        // ("i686-unknown-freebsd", "x86", "freebsd") => &base::TARGET_I686_UNKNOWN_FREEBSD,
        // ("i686-unknown-linux-gnu", "x86", "linux") => &base::TARGET_I686_UNKNOWN_LINUX_GNU,
        // ("i686-unknown-linux-musl", "x86", "linux") => &base::TARGET_I686_UNKNOWN_LINUX_MUSL,
        // ("mips-unknown-linux-gnu", "mips", "linux") => &base::TARGET_MIPS_UNKNOWN_LINUX_GNU,
        // ("mips-unknown-linux-musl", "mips", "linux") => &base::TARGET_MIPS_UNKNOWN_LINUX_MUSL,
        // ("mips64-unknown-linux-gnuabi64", "mips64", "linux") => &base::TARGET_MIPS64_UNKNOWN_LINUX_GNUABI64,
        // ("mips64-unknown-linux-muslabi64", "mips64", "linux") => &base::TARGET_MIPS64_UNKNOWN_LINUX_MUSLABI64,
        // ("mipsel-unknown-linux-gnu", "mips", "linux") => &base::TARGET_MIPSEL_UNKNOWN_LINUX_GNU,
        // ("mipsel-unknown-linux-musl", "mips", "linux") => &base::TARGET_MIPSEL_UNKNOWN_LINUX_MUSL,
        // ("powerpc-unknown-linux-gnu", "powerpc", "linux") => &base::TARGET_POWERPC_UNKNOWN_LINUX_GNU,
        // ("powerpc64-unknown-linux-gnu", "powerpc64", "linux") => &base::TARGET_POWERPC64_UNKNOWN_LINUX_GNU,
        // ("powerpc64le-unknown-linux-gnu", "powerpc64", "linux") => &base::TARGET_POWERPC64LE_UNKNOWN_LINUX_GNU,
        // ("riscv32i-unknown-none-elf", "riscv32", "none") => &base::TARGET_RISCV32I_UNKNOWN_NONE_ELF,
        // ("riscv32imac-unknown-none-elf", "riscv32", "none") => &base::TARGET_RISCV32IMAC_UNKNOWN_NONE_ELF,
        // ("riscv32imafc-unknown-none-elf", "riscv32", "none") => &base::TARGET_RISCV32IMAFC_UNKNOWN_NONE_ELF,
        // ("riscv32gc-unknown-none-elf", "riscv32", "none") => &base::TARGET_RISCV32GC_UNKNOWN_NONE_ELF,
        // ("riscv64gc-unknown-linux-gnu", "riscv64", "linux") => &base::TARGET_RISCV64GC_UNKNOWN_LINUX_GNU,
        // ("riscv64gc-unknown-none-elf", "riscv64", "none") => &base::TARGET_RISCV64GC_UNKNOWN_NONE_ELF,
        // ("s390x-unknown-linux-gnu", "s390x", "linux") => &base::TARGET_S390X_UNKNOWN_LINUX_GNU,
        // ("sparc64-unknown-linux-gnu", "sparc64", "linux") => &base::TARGET_SPARC64_UNKNOWN_LINUX_GNU,
        // ("sparcv9-sun-solaris", "sparc64", "solaris") => &base::TARGET_SPARCV9_SUN_SOLARIS,
        // ("wasm32-unknown-emscripten", "wasm32", "emscripten") => &base::TARGET_WASM32_UNKNOWN_EMSCRIPTEN,
        // ("wasm32-unknown-unknown", "wasm32", "unknown") => &base::TARGET_WASM32_UNKNOWN_UNKNOWN,
        // ("wasm32-wasi", "wasm32", "wasi") => &base::TARGET_WASM32_WASI,
        // ("x86_64-apple-darwin", "x86_64", "darwin") => &apple::TARGET_X86_64_APPLE_DARWIN,
        // ("x86_64-apple-ios", "x86_64", "ios") => &apple::TARGET_X86_64_APPLE_IOS,
        // ("x86_64-fortanix-unknown-sgx", "x86_64", "fortanix-unknown-sgx") => &base::TARGET_X86_64_FORTANIX_UNKNOWN_SGX,
        // ("x86_64-fuchsia", "x86_64", "fuchsia") => &base::TARGET_X86_64_FUCHSIA,
        // ("x86_64-linux-android", "x86_64", "android") => &base::TARGET_X86_64_LINUX_ANDROID,
        // ("x86_64-pc-windows-gnu", "x86_64", "windows") => &base::TARGET_X86_64_PC_WINDOWS_GNU,
        // ("x86_64-pc-windows-msvc", "x86_64", "windows") => &base::TARGET_X86_64_PC_WINDOWS_MSVC,
        // ("x86_64-rumprun-netbsd", "x86_64", "rumprun") => &base::TARGET_X86_64_RUMPRUN_NETBSD,
        // ("x86_64-unknown-freebsd", "x86_64", "freebsd") => &base::TARGET_X86_64_UNKNOWN_FREEBSD,
        // ("x86_64-unknown-illumos", "x86_64", "illumos") => &base::TARGET_X86_64_UNKNOWN_ILLUMOS,
        // ("x86_64-unknown-linux-gnux32", "x86_64", "linux") => &base::TARGET_X86_64_UNKNOWN_LINUX_GNUX32,
        // ("x86_64-unknown-linux-gnu", "x86_64", "linux") => &base::TARGET_X86_64_UNKNOWN_LINUX_GNU,
        // ("x86_64-unknown-linux-musl", "x86_64", "linux") => &base::TARGET_X86_64_UNKNOWN_LINUX_MUSL,
        // ("x86_64-unknown-netbsd", "x86_64", "netbsd") => &base::TARGET_X86_64_UNKNOWN_NETBSD,
        // ("x86_64-unknown-openbsd", "x86_64", "openbsd") => &base::TARGET_X86_64_UNKNOWN_OPENBSD,
        // ("x86_64-unknown-redox", "x86_64", "redox") => &base::TARGET_X86_64_UNKNOWN_REDOX,
        // ("x86_64-unknown-uefi", "x86_64", "uefi") => &base::TARGET_X86_64_UNKNOWN_UEFI,
        // ("x86_64-pc-solaris", "x86_64", "solaris") => &base::TARGET_X86_64_PC_SOLARIS,
        // ("x86_64-sun-solaris", "x86_64", "solaris") => &base::TARGET_X86_64_SUN_SOLARIS,
        // ("x86_64-unknown-l4re-uclibc", "x86_64", "l4re") => &base::TARGET_X86_64_UNKNOWN_L4RE_UCLIBC,
    }
}
