# This file was @generated by cargo2nix 0.12.0.
# It is not intended to be manually edited.

args@{ release ? true
, rootFeatures ? [
    "y/default"
  ]
, rustPackages
, buildRustPackages
, hostPlatform
, hostPlatformCpu ? null
, hostPlatformFeatures ? [ ]
, target ? null
, codegenOpts ? null
, profileOpts ? null
, cargoUnstableFlags ? null
, rustcLinkFlags ? null
, rustcBuildFlags ? null
, mkRustCrate
, rustLib
, lib
, workspaceSrc
, ignoreLockHash
, cargoConfig ? { }
,
}:
let
  nixifiedLockHash = "be8b8f551bc089147c18aa4222ad7c79a1bf705da66bbd4a6c4b310067cb463a";
  workspaceSrc = if args.workspaceSrc == null then ./. else args.workspaceSrc;
  currentLockHash = builtins.hashFile "sha256" (workspaceSrc + /Cargo.lock);
  lockHashIgnored =
    if ignoreLockHash
    then builtins.trace "Ignoring lock hash" ignoreLockHash
    else ignoreLockHash;
in
if !lockHashIgnored && (nixifiedLockHash != currentLockHash) then
  throw ("Cargo.nix ${nixifiedLockHash} is out of sync with Cargo.lock ${currentLockHash}")
else
  let
    inherit (rustLib) fetchCratesIo fetchCrateLocal fetchCrateGit fetchCrateAlternativeRegistry expandFeatures decideProfile genDrvsByProfile;
    cargoConfig' = if cargoConfig != { } then cargoConfig else
    if builtins.pathExists ./.cargo/config then lib.importTOML ./.cargo/config else
    if builtins.pathExists ./.cargo/config.toml then lib.importTOML ./.cargo/config.toml else { };
    profilesByName = { };
    rootFeatures' = expandFeatures rootFeatures;
    overridableMkRustCrate = f:
      let
        drvs = genDrvsByProfile profilesByName ({ profile, profileName }: mkRustCrate ({
          inherit release profile hostPlatformCpu hostPlatformFeatures target profileOpts codegenOpts cargoUnstableFlags rustcLinkFlags rustcBuildFlags;
          cargoConfig = cargoConfig';
        } // (f profileName)));
      in
      { compileMode ? null, profileName ? decideProfile compileMode release }:
      let drv = drvs.${profileName}; in if compileMode == null then drv else drv.override { inherit compileMode; };
  in
  {
    cargo2nixVersion = "0.12.0";
    workspace = {
      y = rustPackages.unknown.y."0.1.0";
    };
    "registry+https://github.com/rust-lang/crates.io-index".boml."0.3.1" = overridableMkRustCrate (profileName: rec {
      name = "boml";
      version = "0.3.1";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "85fdb93f04c73bff54305fa437ffea5449c41edcaadfe882f35836206b166ac5"; };
    });

    "unknown".y."0.1.0" = overridableMkRustCrate (profileName: rec {
      name = "y";
      version = "0.1.0";
      registry = "unknown";
      src = fetchCrateLocal workspaceSrc;
      dependencies = {
        boml = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".boml."0.3.1" { inherit profileName; }).out;
      };
    });

  }
