# This file was @generated by cargo2nix 0.12.0.
# It is not intended to be manually edited.

args@{ release ? true
, rootFeatures ? [
    "rustc_codegen_cranelift/default"
  ]
, rustPackages
, buildRustPackages
, hostPlatform
, hostPlatformCpu ? null
, hostPlatformFeatures ? [ ]
, target ? null
, codegenOpts ? null
, profileOpts ? null
, cargoUnstableFlags ? null
, rustcLinkFlags ? null
, rustcBuildFlags ? null
, mkRustCrate
, rustLib
, lib
, workspaceSrc
, ignoreLockHash
, cargoConfig ? { }
,
}:
let
  nixifiedLockHash = "f4d7ff896792facde801d44b139298f48b65d4a5987dd93d90f39ce2b4727e05";
  workspaceSrc = if args.workspaceSrc == null then ./. else args.workspaceSrc;
  currentLockHash = builtins.hashFile "sha256" (workspaceSrc + /Cargo.lock);
  lockHashIgnored =
    if ignoreLockHash
    then builtins.trace "Ignoring lock hash" ignoreLockHash
    else ignoreLockHash;
in
if !lockHashIgnored && (nixifiedLockHash != currentLockHash) then
  throw ("Cargo.nix ${nixifiedLockHash} is out of sync with Cargo.lock ${currentLockHash}")
else
  let
    inherit (rustLib) fetchCratesIo fetchCrateLocal fetchCrateGit fetchCrateAlternativeRegistry expandFeatures decideProfile genDrvsByProfile;
    cargoConfig' = if cargoConfig != { } then cargoConfig else
    if builtins.pathExists ./.cargo/config then lib.importTOML ./.cargo/config else
    if builtins.pathExists ./.cargo/config.toml then lib.importTOML ./.cargo/config.toml else { };
    profilesByName = { };
    rootFeatures' = expandFeatures rootFeatures;
    overridableMkRustCrate = f:
      let
        drvs = genDrvsByProfile profilesByName ({ profile, profileName }: mkRustCrate ({
          inherit release profile hostPlatformCpu hostPlatformFeatures target profileOpts codegenOpts cargoUnstableFlags rustcLinkFlags rustcBuildFlags;
          cargoConfig = cargoConfig';
        } // (f profileName)));
      in
      { compileMode ? null, profileName ? decideProfile compileMode release }:
      let drv = drvs.${profileName}; in if compileMode == null then drv else drv.override { inherit compileMode; };
  in
  {
    cargo2nixVersion = "0.12.0";
    workspace = {
      rustc_codegen_cranelift = rustPackages.unknown.rustc_codegen_cranelift."0.1.0";
    };
    "registry+https://github.com/rust-lang/crates.io-index".ahash."0.8.12" = overridableMkRustCrate (profileName: rec {
      name = "ahash";
      version = "0.8.12";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "5a15f179cd60c4584b8a8c596927aadc462e27f2ca70c04e0071964a73ba7a75"; };
      dependencies = {
        cfg_if = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cfg-if."1.0.4" { inherit profileName; }).out;
        ${ if !((hostPlatform.parsed.cpu.name == "armv6l" || hostPlatform.parsed.cpu.name == "armv7l") && hostPlatform.parsed.kernel.name == "none") then "once_cell" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".once_cell."1.21.3" { inherit profileName; }).out;
        zerocopy = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".zerocopy."0.8.27" { inherit profileName; }).out;
      };
      buildDependencies = {
        version_check = (buildRustPackages."registry+https://github.com/rust-lang/crates.io-index".version_check."0.9.5" { profileName = "__noProfile"; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".anyhow."1.0.100" = overridableMkRustCrate (profileName: rec {
      name = "anyhow";
      version = "1.0.100";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "a23eb6b1614318a8071c9b2521f36b424b2c83db5eb3a0fead4a6c0809af6e61"; };
      features = builtins.concatLists [
        [ "std" ]
      ];
    });

    "registry+https://github.com/rust-lang/crates.io-index".arbitrary."1.4.2" = overridableMkRustCrate (profileName: rec {
      name = "arbitrary";
      version = "1.4.2";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "c3d036a3c4ab069c7b410a2ce876bd74808d2d0888a82667669f8e783a898bf1"; };
    });

    "registry+https://github.com/rust-lang/crates.io-index".bitflags."1.3.2" = overridableMkRustCrate (profileName: rec {
      name = "bitflags";
      version = "1.3.2";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "bef38d45163c2f1dde094a7dfd33ccf595c92905c8f8f4fdc18d06fb1037718a"; };
      features = builtins.concatLists [
        (lib.optional (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") "default")
      ];
    });

    "registry+https://github.com/rust-lang/crates.io-index".bumpalo."3.19.0" = overridableMkRustCrate (profileName: rec {
      name = "bumpalo";
      version = "3.19.0";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "46c5e41b57b8bba42a04676d81cb89e9ee8e859a1a66f80a5a72e1cb76b34d43"; };
      features = builtins.concatLists [
        [ "default" ]
      ];
    });

    "registry+https://github.com/rust-lang/crates.io-index".cfg-if."1.0.4" = overridableMkRustCrate (profileName: rec {
      name = "cfg-if";
      version = "1.0.4";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "9330f8b2ff13f34540b44e946ef35111825727b38d33286ef986142615121801"; };
    });

    "registry+https://github.com/rust-lang/crates.io-index".cranelift-bforest."0.113.1" = overridableMkRustCrate (profileName: rec {
      name = "cranelift-bforest";
      version = "0.113.1";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "540b193ff98b825a1f250a75b3118911af918a734154c69d80bcfcf91e7e9522"; };
      dependencies = {
        cranelift_entity = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cranelift-entity."0.113.1" { inherit profileName; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".cranelift-bitset."0.113.1" = overridableMkRustCrate (profileName: rec {
      name = "cranelift-bitset";
      version = "0.113.1";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "c7cb269598b9557ab942d687d3c1086d77c4b50dcf35813f3a65ba306fd42279"; };
    });

    "registry+https://github.com/rust-lang/crates.io-index".cranelift-codegen."0.113.1" = overridableMkRustCrate (profileName: rec {
      name = "cranelift-codegen";
      version = "0.113.1";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "46566d7c83a8bff4150748d66020f4c7224091952aa4b4df1ec4959c39d937a1"; };
      features = builtins.concatLists [
        [ "all-native-arch" ]
        [ "arm64" ]
        [ "gimli" ]
        [ "riscv64" ]
        [ "s390x" ]
        [ "std" ]
        [ "unwind" ]
        [ "x86" ]
      ];
      dependencies = {
        bumpalo = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".bumpalo."3.19.0" { inherit profileName; }).out;
        cranelift_bforest = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cranelift-bforest."0.113.1" { inherit profileName; }).out;
        cranelift_bitset = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cranelift-bitset."0.113.1" { inherit profileName; }).out;
        cranelift_codegen_shared = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cranelift-codegen-shared."0.113.1" { inherit profileName; }).out;
        cranelift_control = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cranelift-control."0.113.1" { inherit profileName; }).out;
        cranelift_entity = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cranelift-entity."0.113.1" { inherit profileName; }).out;
        gimli = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".gimli."0.31.1" { inherit profileName; }).out;
        hashbrown = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".hashbrown."0.14.5" { inherit profileName; }).out;
        log = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".log."0.4.28" { inherit profileName; }).out;
        regalloc2 = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".regalloc2."0.10.2" { inherit profileName; }).out;
        rustc_hash = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".rustc-hash."2.1.1" { inherit profileName; }).out;
        smallvec = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".smallvec."1.15.1" { inherit profileName; }).out;
        target_lexicon = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".target-lexicon."0.12.16" { inherit profileName; }).out;
      };
      buildDependencies = {
        cranelift_codegen_meta = (buildRustPackages."registry+https://github.com/rust-lang/crates.io-index".cranelift-codegen-meta."0.113.1" { profileName = "__noProfile"; }).out;
        cranelift_isle = (buildRustPackages."registry+https://github.com/rust-lang/crates.io-index".cranelift-isle."0.113.1" { profileName = "__noProfile"; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".cranelift-codegen-meta."0.113.1" = overridableMkRustCrate (profileName: rec {
      name = "cranelift-codegen-meta";
      version = "0.113.1";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "2df8a86a34236cc75a8a6a271973da779c2aeb36c43b6e14da474cf931317082"; };
      dependencies = {
        cranelift_codegen_shared = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cranelift-codegen-shared."0.113.1" { inherit profileName; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".cranelift-codegen-shared."0.113.1" = overridableMkRustCrate (profileName: rec {
      name = "cranelift-codegen-shared";
      version = "0.113.1";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "cf75340b6a57b7c7c1b74f10d3d90883ee6d43a554be8131a4046c2ebcf5eb65"; };
    });

    "registry+https://github.com/rust-lang/crates.io-index".cranelift-control."0.113.1" = overridableMkRustCrate (profileName: rec {
      name = "cranelift-control";
      version = "0.113.1";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "2e84495bc5d23d86aad8c86f8ade4af765b94882af60d60e271d3153942f1978"; };
      features = builtins.concatLists [
        [ "default" ]
        [ "fuzz" ]
      ];
      dependencies = {
        arbitrary = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".arbitrary."1.4.2" { inherit profileName; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".cranelift-entity."0.113.1" = overridableMkRustCrate (profileName: rec {
      name = "cranelift-entity";
      version = "0.113.1";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "963c17147b80df351965e57c04d20dbedc85bcaf44c3436780a59a3f1ff1b1c2"; };
      dependencies = {
        cranelift_bitset = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cranelift-bitset."0.113.1" { inherit profileName; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".cranelift-frontend."0.113.1" = overridableMkRustCrate (profileName: rec {
      name = "cranelift-frontend";
      version = "0.113.1";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "727f02acbc4b4cb2ba38a6637101d579db50190df1dd05168c68e762851a3dd5"; };
      features = builtins.concatLists [
        [ "default" ]
        [ "std" ]
      ];
      dependencies = {
        cranelift_codegen = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cranelift-codegen."0.113.1" { inherit profileName; }).out;
        log = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".log."0.4.28" { inherit profileName; }).out;
        smallvec = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".smallvec."1.15.1" { inherit profileName; }).out;
        target_lexicon = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".target-lexicon."0.12.16" { inherit profileName; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".cranelift-isle."0.113.1" = overridableMkRustCrate (profileName: rec {
      name = "cranelift-isle";
      version = "0.113.1";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "32b00cc2e03c748f2531eea01c871f502b909d30295fdcad43aec7bf5c5b4667"; };
      features = builtins.concatLists [
        [ "default" ]
      ];
    });

    "registry+https://github.com/rust-lang/crates.io-index".cranelift-jit."0.113.1" = overridableMkRustCrate (profileName: rec {
      name = "cranelift-jit";
      version = "0.113.1";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "f74630af581f32b99c8f4e06ee45799383ecc0795e3ff8aa86b7584bb2d643fd"; };
      features = builtins.concatLists [
        (lib.optional (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") "default")
      ];
      dependencies = {
        ${ if rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features" then "anyhow" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".anyhow."1.0.100" { inherit profileName; }).out;
        ${ if rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features" then "cranelift_codegen" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cranelift-codegen."0.113.1" { inherit profileName; }).out;
        ${ if rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features" then "cranelift_control" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cranelift-control."0.113.1" { inherit profileName; }).out;
        ${ if rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features" then "cranelift_entity" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cranelift-entity."0.113.1" { inherit profileName; }).out;
        ${ if rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features" then "cranelift_module" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cranelift-module."0.113.1" { inherit profileName; }).out;
        ${ if rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features" then "cranelift_native" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cranelift-native."0.113.1" { inherit profileName; }).out;
        ${ if rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features" then "libc" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".libc."0.2.177" { inherit profileName; }).out;
        ${ if rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features" then "log" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".log."0.4.28" { inherit profileName; }).out;
        ${ if rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features" then "region" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".region."3.0.2" { inherit profileName; }).out;
        ${ if rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features" then "target_lexicon" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".target-lexicon."0.12.16" { inherit profileName; }).out;
        ${ if rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features" then "wasmtime_jit_icache_coherence" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".wasmtime-jit-icache-coherence."26.0.1" { inherit profileName; }).out;
        ${ if (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") && hostPlatform.isWindows then "windows_sys" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".windows-sys."0.59.0" { inherit profileName; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".cranelift-module."0.113.1" = overridableMkRustCrate (profileName: rec {
      name = "cranelift-module";
      version = "0.113.1";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "6aaa16c4f18a15be310df221ea544f516acc42fc58ca96e09a3d08651744efa1"; };
      features = builtins.concatLists [
        [ "default" ]
        [ "std" ]
      ];
      dependencies = {
        anyhow = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".anyhow."1.0.100" { inherit profileName; }).out;
        cranelift_codegen = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cranelift-codegen."0.113.1" { inherit profileName; }).out;
        cranelift_control = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cranelift-control."0.113.1" { inherit profileName; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".cranelift-native."0.113.1" = overridableMkRustCrate (profileName: rec {
      name = "cranelift-native";
      version = "0.113.1";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "bbeaf978dc7c1a2de8bbb9162510ed218eb156697bc45590b8fbdd69bb08e8de"; };
      features = builtins.concatLists [
        [ "default" ]
        [ "std" ]
      ];
      dependencies = {
        cranelift_codegen = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cranelift-codegen."0.113.1" { inherit profileName; }).out;
        ${ if hostPlatform.parsed.cpu.name == "s390x" || hostPlatform.parsed.cpu.name == "riscv64" then "libc" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".libc."0.2.177" { inherit profileName; }).out;
        target_lexicon = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".target-lexicon."0.12.16" { inherit profileName; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".cranelift-object."0.113.1" = overridableMkRustCrate (profileName: rec {
      name = "cranelift-object";
      version = "0.113.1";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "3ff68f0ef71bdfd21c2b94743a53347abfd82d78a2a36dc753f7c33d063ee25d"; };
      dependencies = {
        anyhow = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".anyhow."1.0.100" { inherit profileName; }).out;
        cranelift_codegen = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cranelift-codegen."0.113.1" { inherit profileName; }).out;
        cranelift_control = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cranelift-control."0.113.1" { inherit profileName; }).out;
        cranelift_module = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cranelift-module."0.113.1" { inherit profileName; }).out;
        log = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".log."0.4.28" { inherit profileName; }).out;
        object = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".object."0.36.7" { inherit profileName; }).out;
        target_lexicon = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".target-lexicon."0.12.16" { inherit profileName; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".crc32fast."1.5.0" = overridableMkRustCrate (profileName: rec {
      name = "crc32fast";
      version = "1.5.0";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "9481c1c90cbf2ac953f07c8d4a58aa3945c425b7185c9154d67a65e4230da511"; };
      features = builtins.concatLists [
        [ "std" ]
      ];
      dependencies = {
        cfg_if = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cfg-if."1.0.4" { inherit profileName; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".equivalent."1.0.2" = overridableMkRustCrate (profileName: rec {
      name = "equivalent";
      version = "1.0.2";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "877a4ace8713b0bcf2a4e7eec82529c029f1d0619886d18145fea96c3ffe5c0f"; };
    });

    "registry+https://github.com/rust-lang/crates.io-index".fallible-iterator."0.3.0" = overridableMkRustCrate (profileName: rec {
      name = "fallible-iterator";
      version = "0.3.0";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "2acce4a10f12dc2fb14a218589d4f1f62ef011b2d0cc4b3cb1bba8e94da14649"; };
      features = builtins.concatLists [
        [ "alloc" ]
        [ "std" ]
      ];
    });

    "registry+https://github.com/rust-lang/crates.io-index".foldhash."0.1.5" = overridableMkRustCrate (profileName: rec {
      name = "foldhash";
      version = "0.1.5";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "d9c4f5dac5e15c24eb999c26181a6ca40b39fe946cbe4c263c7209467bc83af2"; };
    });

    "registry+https://github.com/rust-lang/crates.io-index".gimli."0.31.1" = overridableMkRustCrate (profileName: rec {
      name = "gimli";
      version = "0.31.1";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "07e28edb80900c19c28f1072f2e8aeca7fa06b23cd4169cefe1af5aa3260783f"; };
      features = builtins.concatLists [
        [ "read" ]
        [ "read-core" ]
        [ "std" ]
        [ "write" ]
      ];
      dependencies = {
        fallible_iterator = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".fallible-iterator."0.3.0" { inherit profileName; }).out;
        indexmap = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".indexmap."2.12.0" { inherit profileName; }).out;
        stable_deref_trait = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".stable_deref_trait."1.2.1" { inherit profileName; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".hashbrown."0.14.5" = overridableMkRustCrate (profileName: rec {
      name = "hashbrown";
      version = "0.14.5";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "e5274423e17b7c9fc20b6e7e208532f9b19825d82dfd615708b70edd83df41f1"; };
      features = builtins.concatLists [
        [ "ahash" ]
        [ "raw" ]
      ];
      dependencies = {
        ahash = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".ahash."0.8.12" { inherit profileName; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".hashbrown."0.15.5" = overridableMkRustCrate (profileName: rec {
      name = "hashbrown";
      version = "0.15.5";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "9229cfe53dfd69f0609a49f65461bd93001ea1ef889cd5529dd176593f5338a1"; };
      features = builtins.concatLists [
        [ "default-hasher" ]
      ];
      dependencies = {
        foldhash = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".foldhash."0.1.5" { inherit profileName; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".hashbrown."0.16.0" = overridableMkRustCrate (profileName: rec {
      name = "hashbrown";
      version = "0.16.0";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "5419bdc4f6a9207fbeba6d11b604d481addf78ecd10c11ad51e76c2f6482748d"; };
    });

    "registry+https://github.com/rust-lang/crates.io-index".indexmap."2.12.0" = overridableMkRustCrate (profileName: rec {
      name = "indexmap";
      version = "2.12.0";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "6717a8d2a5a929a1a2eb43a12812498ed141a0bcfb7e8f7844fbdbe4303bba9f"; };
      features = builtins.concatLists [
        [ "default" ]
        [ "std" ]
      ];
      dependencies = {
        equivalent = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".equivalent."1.0.2" { inherit profileName; }).out;
        hashbrown = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".hashbrown."0.16.0" { inherit profileName; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".libc."0.2.177" = overridableMkRustCrate (profileName: rec {
      name = "libc";
      version = "0.2.177";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "2874a2af47a2325c2001a6e6fad9b16a53b802102b528163885171cf92b15976"; };
      features = builtins.concatLists [
        [ "default" ]
        [ "std" ]
      ];
    });

    "registry+https://github.com/rust-lang/crates.io-index".libloading."0.8.9" = overridableMkRustCrate (profileName: rec {
      name = "libloading";
      version = "0.8.9";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "d7c4b02199fee7c5d21a5ae7d8cfa79a6ef5bb2fc834d6e9058e89c825efdc55"; };
      dependencies = {
        ${ if (rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/libloading" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") && hostPlatform.isUnix then "cfg_if" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cfg-if."1.0.4" { inherit profileName; }).out;
        ${ if (rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/libloading" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") && hostPlatform.isWindows then "windows_link" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".windows-link."0.2.1" { inherit profileName; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".log."0.4.28" = overridableMkRustCrate (profileName: rec {
      name = "log";
      version = "0.4.28";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "34080505efa8e45a4b816c349525ebe327ceaa8559756f0356cba97ef3bf7432"; };
    });

    "registry+https://github.com/rust-lang/crates.io-index".mach2."0.4.3" = overridableMkRustCrate (profileName: rec {
      name = "mach2";
      version = "0.4.3";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "d640282b302c0bb0a2a8e0233ead9035e3bed871f0b7e81fe4a1ec829765db44"; };
      features = builtins.concatLists [
        (lib.optional (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") "default")
      ];
      dependencies = {
        ${ if (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") && (hostPlatform.parsed.kernel.name == "darwin" || hostPlatform.parsed.kernel.name == "ios") then "libc" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".libc."0.2.177" { inherit profileName; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".memchr."2.7.6" = overridableMkRustCrate (profileName: rec {
      name = "memchr";
      version = "2.7.6";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "f52b00d39961fc5b2736ea853c9cc86238e165017a493d1d5c8eac6bdc4cc273"; };
      features = builtins.concatLists [
        [ "alloc" ]
        [ "std" ]
      ];
    });

    "registry+https://github.com/rust-lang/crates.io-index".object."0.36.7" = overridableMkRustCrate (profileName: rec {
      name = "object";
      version = "0.36.7";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "62948e14d923ea95ea2c7c86c71013138b66525b86bdc08d2dcc262bdb497b87"; };
      features = builtins.concatLists [
        [ "archive" ]
        [ "coff" ]
        [ "elf" ]
        [ "macho" ]
        [ "pe" ]
        [ "read_core" ]
        [ "std" ]
        [ "write" ]
        [ "write_core" ]
        [ "write_std" ]
        [ "xcoff" ]
      ];
      dependencies = {
        crc32fast = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".crc32fast."1.5.0" { inherit profileName; }).out;
        hashbrown = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".hashbrown."0.15.5" { inherit profileName; }).out;
        indexmap = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".indexmap."2.12.0" { inherit profileName; }).out;
        memchr = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".memchr."2.7.6" { inherit profileName; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".once_cell."1.21.3" = overridableMkRustCrate (profileName: rec {
      name = "once_cell";
      version = "1.21.3";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "42f5e15c9953c5e4ccceeb2e7382a716482c34515315f7b03532b8b4e8393d2d"; };
      features = builtins.concatLists [
        [ "alloc" ]
        [ "race" ]
      ];
    });

    "registry+https://github.com/rust-lang/crates.io-index".proc-macro2."1.0.101" = overridableMkRustCrate (profileName: rec {
      name = "proc-macro2";
      version = "1.0.101";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "89ae43fd86e4158d6db51ad8e2b80f313af9cc74f5c0e03ccb87de09998732de"; };
      features = builtins.concatLists [
        [ "default" ]
        [ "proc-macro" ]
      ];
      dependencies = {
        unicode_ident = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".unicode-ident."1.0.19" { inherit profileName; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".quote."1.0.41" = overridableMkRustCrate (profileName: rec {
      name = "quote";
      version = "1.0.41";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "ce25767e7b499d1b604768e7cde645d14cc8584231ea6b295e9c9eb22c02e1d1"; };
      features = builtins.concatLists [
        [ "default" ]
        [ "proc-macro" ]
      ];
      dependencies = {
        proc_macro2 = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".proc-macro2."1.0.101" { inherit profileName; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".regalloc2."0.10.2" = overridableMkRustCrate (profileName: rec {
      name = "regalloc2";
      version = "0.10.2";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "12908dbeb234370af84d0579b9f68258a0f67e201412dd9a2814e6f45b2fc0f0"; };
      features = builtins.concatLists [
        [ "checker" ]
        [ "default" ]
        [ "std" ]
      ];
      dependencies = {
        hashbrown = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".hashbrown."0.14.5" { inherit profileName; }).out;
        log = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".log."0.4.28" { inherit profileName; }).out;
        rustc_hash = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".rustc-hash."2.1.1" { inherit profileName; }).out;
        slice_group_by = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".slice-group-by."0.3.1" { inherit profileName; }).out;
        smallvec = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".smallvec."1.15.1" { inherit profileName; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".region."3.0.2" = overridableMkRustCrate (profileName: rec {
      name = "region";
      version = "3.0.2";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "e6b6ebd13bc009aef9cd476c1310d49ac354d36e240cf1bd753290f3dc7199a7"; };
      dependencies = {
        ${ if rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features" then "bitflags" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".bitflags."1.3.2" { inherit profileName; }).out;
        ${ if rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features" then "libc" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".libc."0.2.177" { inherit profileName; }).out;
        ${ if (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") && (hostPlatform.parsed.kernel.name == "darwin" || hostPlatform.parsed.kernel.name == "ios") then "mach2" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".mach2."0.4.3" { inherit profileName; }).out;
        ${ if (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") && hostPlatform.isWindows then "windows_sys" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".windows-sys."0.52.0" { inherit profileName; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".rustc-hash."2.1.1" = overridableMkRustCrate (profileName: rec {
      name = "rustc-hash";
      version = "2.1.1";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "357703d41365b4b27c590e3ed91eabb1b663f07c4c084095e60cbed4362dff0d"; };
      features = builtins.concatLists [
        [ "default" ]
        [ "std" ]
      ];
    });

    "unknown".rustc_codegen_cranelift."0.1.0" = overridableMkRustCrate (profileName: rec {
      name = "rustc_codegen_cranelift";
      version = "0.1.0";
      registry = "unknown";
      src = fetchCrateLocal workspaceSrc;
      features = builtins.concatLists [
        (lib.optional (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") "cranelift-jit")
        (lib.optional (rootFeatures' ? "rustc_codegen_cranelift/inline_asm_sym" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") "inline_asm_sym")
        (lib.optional (rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") "jit")
        (lib.optional (rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/libloading" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") "libloading")
        (lib.optional (rootFeatures' ? "rustc_codegen_cranelift/unstable-features") "unstable-features")
      ];
      dependencies = {
        cranelift_codegen = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cranelift-codegen."0.113.1" { inherit profileName; }).out;
        cranelift_frontend = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cranelift-frontend."0.113.1" { inherit profileName; }).out;
        ${ if rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features" then "cranelift_jit" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cranelift-jit."0.113.1" { inherit profileName; }).out;
        cranelift_module = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cranelift-module."0.113.1" { inherit profileName; }).out;
        cranelift_native = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cranelift-native."0.113.1" { inherit profileName; }).out;
        cranelift_object = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cranelift-object."0.113.1" { inherit profileName; }).out;
        gimli = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".gimli."0.31.1" { inherit profileName; }).out;
        indexmap = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".indexmap."2.12.0" { inherit profileName; }).out;
        ${ if rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/libloading" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features" then "libloading" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".libloading."0.8.9" { inherit profileName; }).out;
        object = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".object."0.36.7" { inherit profileName; }).out;
        smallvec = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".smallvec."1.15.1" { inherit profileName; }).out;
        target_lexicon = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".target-lexicon."0.12.16" { inherit profileName; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".slice-group-by."0.3.1" = overridableMkRustCrate (profileName: rec {
      name = "slice-group-by";
      version = "0.3.1";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "826167069c09b99d56f31e9ae5c99049e932a98c9dc2dac47645b08dbbf76ba7"; };
    });

    "registry+https://github.com/rust-lang/crates.io-index".smallvec."1.15.1" = overridableMkRustCrate (profileName: rec {
      name = "smallvec";
      version = "1.15.1";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "67b1b7a3b5fe4f1376887184045fcf45c69e92af734b7aaddc05fb777b6fbd03"; };
      features = builtins.concatLists [
        [ "union" ]
      ];
    });

    "registry+https://github.com/rust-lang/crates.io-index".stable_deref_trait."1.2.1" = overridableMkRustCrate (profileName: rec {
      name = "stable_deref_trait";
      version = "1.2.1";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "6ce2be8dc25455e1f91df71bfa12ad37d7af1092ae736f3a6cd0e37bc7810596"; };
      features = builtins.concatLists [
        [ "alloc" ]
        [ "std" ]
      ];
    });

    "registry+https://github.com/rust-lang/crates.io-index".syn."2.0.107" = overridableMkRustCrate (profileName: rec {
      name = "syn";
      version = "2.0.107";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "2a26dbd934e5451d21ef060c018dae56fc073894c5a7896f882928a76e6d081b"; };
      features = builtins.concatLists [
        [ "clone-impls" ]
        [ "default" ]
        [ "derive" ]
        [ "full" ]
        [ "parsing" ]
        [ "printing" ]
        [ "proc-macro" ]
      ];
      dependencies = {
        proc_macro2 = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".proc-macro2."1.0.101" { inherit profileName; }).out;
        quote = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".quote."1.0.41" { inherit profileName; }).out;
        unicode_ident = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".unicode-ident."1.0.19" { inherit profileName; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".target-lexicon."0.12.16" = overridableMkRustCrate (profileName: rec {
      name = "target-lexicon";
      version = "0.12.16";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "61c41af27dd6d1e27b1b16b489db798443478cef1f06a660c96db617ba5de3b1"; };
      features = builtins.concatLists [
        [ "default" ]
      ];
    });

    "registry+https://github.com/rust-lang/crates.io-index".unicode-ident."1.0.19" = overridableMkRustCrate (profileName: rec {
      name = "unicode-ident";
      version = "1.0.19";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "f63a545481291138910575129486daeaf8ac54aee4387fe7906919f7830c7d9d"; };
    });

    "registry+https://github.com/rust-lang/crates.io-index".version_check."0.9.5" = overridableMkRustCrate (profileName: rec {
      name = "version_check";
      version = "0.9.5";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "0b928f33d975fc6ad9f86c8f283853ad26bdd5b10b7f1542aa2fa15e2289105a"; };
    });

    "registry+https://github.com/rust-lang/crates.io-index".wasmtime-jit-icache-coherence."26.0.1" = overridableMkRustCrate (profileName: rec {
      name = "wasmtime-jit-icache-coherence";
      version = "26.0.1";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "da47fba49af72581bc0dc67c8faaf5ee550e6f106e285122a184a675193701a5"; };
      dependencies = {
        ${ if rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features" then "anyhow" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".anyhow."1.0.100" { inherit profileName; }).out;
        ${ if rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features" then "cfg_if" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".cfg-if."1.0.4" { inherit profileName; }).out;
        ${ if (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") && (hostPlatform.parsed.kernel.name == "linux" || hostPlatform.parsed.kernel.name == "darwin" || hostPlatform.parsed.kernel.name == "freebsd" || hostPlatform.parsed.kernel.name == "android") then "libc" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".libc."0.2.177" { inherit profileName; }).out;
        ${ if (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") && hostPlatform.parsed.kernel.name == "windows" then "windows_sys" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".windows-sys."0.59.0" { inherit profileName; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".windows-link."0.2.1" = overridableMkRustCrate (profileName: rec {
      name = "windows-link";
      version = "0.2.1";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "f0805222e57f7521d6a62e36fa9163bc891acd422f971defe97d64e70d0a4fe5"; };
    });

    "registry+https://github.com/rust-lang/crates.io-index".windows-sys."0.52.0" = overridableMkRustCrate (profileName: rec {
      name = "windows-sys";
      version = "0.52.0";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "282be5f36a8ce781fad8c8ae18fa3f9beff57ec1b52cb3de0789201425d9a33d"; };
      features = builtins.concatLists [
        (lib.optional (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") "Win32")
        (lib.optional (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") "Win32_Foundation")
        (lib.optional (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") "Win32_System")
        (lib.optional (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") "Win32_System_Diagnostics")
        (lib.optional (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") "Win32_System_Diagnostics_Debug")
        (lib.optional (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") "Win32_System_Memory")
        (lib.optional (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") "Win32_System_SystemInformation")
        (lib.optional (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") "default")
      ];
      dependencies = {
        ${ if rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features" then "windows_targets" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".windows-targets."0.52.6" { inherit profileName; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".windows-sys."0.59.0" = overridableMkRustCrate (profileName: rec {
      name = "windows-sys";
      version = "0.59.0";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "1e38bc4d79ed67fd075bcc251a1c39b32a1776bbe92e5bef1f0bf1f8c531853b"; };
      features = builtins.concatLists [
        (lib.optional (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") "Win32")
        (lib.optional (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") "Win32_Foundation")
        (lib.optional (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") "Win32_System")
        (lib.optional (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") "Win32_System_Diagnostics")
        (lib.optional (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") "Win32_System_Diagnostics_Debug")
        (lib.optional (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") "Win32_System_LibraryLoader")
        (lib.optional (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") "Win32_System_Memory")
        (lib.optional (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") "Win32_System_Threading")
        (lib.optional (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") "default")
      ];
      dependencies = {
        ${ if rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features" then "windows_targets" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".windows-targets."0.52.6" { inherit profileName; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".windows-targets."0.52.6" = overridableMkRustCrate (profileName: rec {
      name = "windows-targets";
      version = "0.52.6";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "9b724f72796e036ab90c1021d4780d4d3d648aca59e491e6b98e725b84e99973"; };
      dependencies = {
        ${ if (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") && hostPlatform.config == "aarch64-pc-windows-gnullvm" then "windows_aarch64_gnullvm" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".windows_aarch64_gnullvm."0.52.6" { inherit profileName; }).out;
        ${ if (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") && hostPlatform.parsed.cpu.name == "aarch64" && hostPlatform.parsed.abi.name == "msvc" then "windows_aarch64_msvc" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".windows_aarch64_msvc."0.52.6" { inherit profileName; }).out;
        ${ if (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") && hostPlatform.parsed.cpu.name == "i686" && hostPlatform.parsed.abi.name == "gnu" then "windows_i686_gnu" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".windows_i686_gnu."0.52.6" { inherit profileName; }).out;
        ${ if (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") && hostPlatform.config == "i686-pc-windows-gnullvm" then "windows_i686_gnullvm" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".windows_i686_gnullvm."0.52.6" { inherit profileName; }).out;
        ${ if (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") && hostPlatform.parsed.cpu.name == "i686" && hostPlatform.parsed.abi.name == "msvc" then "windows_i686_msvc" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".windows_i686_msvc."0.52.6" { inherit profileName; }).out;
        ${ if (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") && hostPlatform.parsed.cpu.name == "x86_64" && hostPlatform.parsed.abi.name == "gnu" then "windows_x86_64_gnu" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".windows_x86_64_gnu."0.52.6" { inherit profileName; }).out;
        ${ if (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") && hostPlatform.config == "x86_64-pc-windows-gnullvm" then "windows_x86_64_gnullvm" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".windows_x86_64_gnullvm."0.52.6" { inherit profileName; }).out;
        ${ if (rootFeatures' ? "rustc_codegen_cranelift/cranelift-jit" || rootFeatures' ? "rustc_codegen_cranelift/jit" || rootFeatures' ? "rustc_codegen_cranelift/unstable-features") && (hostPlatform.parsed.cpu.name == "x86_64" || hostPlatform.parsed.cpu.name == "arm64ec") && hostPlatform.parsed.abi.name == "msvc" then "windows_x86_64_msvc" else null } = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".windows_x86_64_msvc."0.52.6" { inherit profileName; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".windows_aarch64_gnullvm."0.52.6" = overridableMkRustCrate (profileName: rec {
      name = "windows_aarch64_gnullvm";
      version = "0.52.6";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "32a4622180e7a0ec044bb555404c800bc9fd9ec262ec147edd5989ccd0c02cd3"; };
    });

    "registry+https://github.com/rust-lang/crates.io-index".windows_aarch64_msvc."0.52.6" = overridableMkRustCrate (profileName: rec {
      name = "windows_aarch64_msvc";
      version = "0.52.6";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "09ec2a7bb152e2252b53fa7803150007879548bc709c039df7627cabbd05d469"; };
    });

    "registry+https://github.com/rust-lang/crates.io-index".windows_i686_gnu."0.52.6" = overridableMkRustCrate (profileName: rec {
      name = "windows_i686_gnu";
      version = "0.52.6";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "8e9b5ad5ab802e97eb8e295ac6720e509ee4c243f69d781394014ebfe8bbfa0b"; };
    });

    "registry+https://github.com/rust-lang/crates.io-index".windows_i686_gnullvm."0.52.6" = overridableMkRustCrate (profileName: rec {
      name = "windows_i686_gnullvm";
      version = "0.52.6";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "0eee52d38c090b3caa76c563b86c3a4bd71ef1a819287c19d586d7334ae8ed66"; };
    });

    "registry+https://github.com/rust-lang/crates.io-index".windows_i686_msvc."0.52.6" = overridableMkRustCrate (profileName: rec {
      name = "windows_i686_msvc";
      version = "0.52.6";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "240948bc05c5e7c6dabba28bf89d89ffce3e303022809e73deaefe4f6ec56c66"; };
    });

    "registry+https://github.com/rust-lang/crates.io-index".windows_x86_64_gnu."0.52.6" = overridableMkRustCrate (profileName: rec {
      name = "windows_x86_64_gnu";
      version = "0.52.6";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "147a5c80aabfbf0c7d901cb5895d1de30ef2907eb21fbbab29ca94c5b08b1a78"; };
    });

    "registry+https://github.com/rust-lang/crates.io-index".windows_x86_64_gnullvm."0.52.6" = overridableMkRustCrate (profileName: rec {
      name = "windows_x86_64_gnullvm";
      version = "0.52.6";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "24d5b23dc417412679681396f2b49f3de8c1473deb516bd34410872eff51ed0d"; };
    });

    "registry+https://github.com/rust-lang/crates.io-index".windows_x86_64_msvc."0.52.6" = overridableMkRustCrate (profileName: rec {
      name = "windows_x86_64_msvc";
      version = "0.52.6";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "589f6da84c646204747d1270a2a5661ea66ed1cced2631d546fdfb155959f9ec"; };
    });

    "registry+https://github.com/rust-lang/crates.io-index".zerocopy."0.8.27" = overridableMkRustCrate (profileName: rec {
      name = "zerocopy";
      version = "0.8.27";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "0894878a5fa3edfd6da3f88c4805f4c8558e2b996227a3d864f47fe11e38282c"; };
      features = builtins.concatLists [
        [ "simd" ]
      ];
      dependencies = {
        ${ if false then "zerocopy_derive" else null } = (buildRustPackages."registry+https://github.com/rust-lang/crates.io-index".zerocopy-derive."0.8.27" { profileName = "__noProfile"; }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".zerocopy-derive."0.8.27" = overridableMkRustCrate (profileName: rec {
      name = "zerocopy-derive";
      version = "0.8.27";
      registry = "registry+https://github.com/rust-lang/crates.io-index";
      src = fetchCratesIo { inherit name version; sha256 = "88d2b8d9c68ad2b9e4340d7832716a4d21a22a1154777ad56ea55c51a9cf3831"; };
      dependencies = {
        proc_macro2 = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".proc-macro2."1.0.101" { inherit profileName; }).out;
        quote = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".quote."1.0.41" { inherit profileName; }).out;
        syn = (rustPackages."registry+https://github.com/rust-lang/crates.io-index".syn."2.0.107" { inherit profileName; }).out;
      };
    });

  }
