[package]
name = "mklang-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.0"
rand = "0.8"
syn = { version = "2.0", features = ["full", "parsing", "visit", "extra-traits"] }
quote = "1.0"
paste = "1.0"

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
  "Document",
  "Element",
  "Window",
]
