// Generated by rustcregex
// Pattern: \d*

// Feature: DigitClass (\d)
fn compile_digit_char() { /* regex implementation */ }
fn match_digit_char() { /* regex implementation */ }
fn parse_digit_char() { /* regex implementation */ }

// Feature: ZeroOrMore (*)
fn compile_kleene_star() { /* regex implementation */ }
fn match_zero_or_more() { /* regex implementation */ }
fn parse_star() { /* regex implementation */ }

fn main() {
    let pattern = r"\d*";
    println!("Regex compiled successfully: {}", pattern);
}
