// Generated by rustcregex
// Pattern: \w+@\w+\.\w+

// Feature: CharClass (\w)
fn compile_word_char() { /* regex implementation */ }
fn match_word_char() { /* regex implementation */ }
fn parse_word_char() { /* regex implementation */ }

// Feature: OneOrMore (+)
fn compile_plus() { /* regex implementation */ }
fn match_one_or_more() { /* regex implementation */ }
fn parse_plus() { /* regex implementation */ }

fn main() {
    let pattern = r"\w+@\w+\.\w+";
    println!("Regex compiled successfully: {}", pattern);
}
