// Generated by rustcregex
// Pattern: ^hello$

// Feature: StartAnchor (^)
fn compile_start_anchor() { /* regex implementation */ }
fn match_start() { /* regex implementation */ }
fn parse_caret() { /* regex implementation */ }

// Feature: EndAnchor ($)
fn compile_end_anchor() { /* regex implementation */ }
fn match_end() { /* regex implementation */ }
fn parse_dollar() { /* regex implementation */ }

fn main() {
    let pattern = r"^hello$";
    println!("Regex compiled successfully: {}", pattern);
}
