// Generated by mkdbuild
// Target Level: 0

// Level 0 Implementation
#[cfg(level_0)]
mod level_impl {
    pub fn parse_const() {
        println!("Executing parse_const (Level 0)");
    }
    pub fn compile_literal() {
        println!("Executing compile_literal (Level 0)");
    }
}

fn main() {
    println!("Minimal Rust Compiler");
    let programs = vec![
        "const x = 1;",
        "const y = true;", 
        "const z = 1 + 2;",
    ];
    for program in programs {
        println!("Compiling: {}", program);
        #[cfg(level_0)]
        println!("Result: {}", compiler::compile(program));
        #[cfg(level_1)] 
        println!("Result: {}", compiler::compile(program));
        #[cfg(level_2)]
        println!("Result: {}", compiler::compile(program));
    }
}
#[cfg(level_0)]
mod compiler {
    pub fn parse_const() { println!("parse_const"); }
    pub fn compile_literal() { println!("compile_literal"); }
    pub fn compile(input: &str) -> String {
        let tokens: Vec<&str> = input.split_whitespace().collect();
        if tokens.len() == 4 && tokens[0] == "const" && tokens[2] == "=" {
            format!("SUCCESS: {}", input)
        } else {
            "ERROR".to_string()
        }
    }
}
#[cfg(level_1)]
mod compiler {
    pub fn parse_const() { println!("parse_const"); }
    pub fn compile_literal() { println!("compile_literal"); }
    pub fn parse_bool() { println!("parse_bool"); }
    pub fn compile_bool() { println!("compile_bool"); }
    pub fn compile(input: &str) -> String {
        let tokens: Vec<&str> = input.split_whitespace().collect();
        if tokens.len() == 4 && tokens[0] == "const" && tokens[2] == "=" {
            let value = tokens[3].trim_end_matches(';');
            match value {
                "1"|"2"|"3"|"4"|"5"|"6"|"7"|"8"|"9"|"0" => format!("SUCCESS: Integer {}", input),
                "true"|"false" => format!("SUCCESS: Boolean {}", input),
                _ => "ERROR".to_string()
            }
        } else {
            "ERROR".to_string()
        }
    }
}
#[cfg(level_2)]
mod compiler {
    pub fn parse_const() { println!("parse_const"); }
    pub fn compile_literal() { println!("compile_literal"); }
    pub fn parse_bool() { println!("parse_bool"); }
    pub fn compile_bool() { println!("compile_bool"); }
    pub fn parse_expr() { println!("parse_expr"); }
    pub fn compile_binop() { println!("compile_binop"); }
    pub fn compile(input: &str) -> String {
        if input.contains('+') || input.contains('-') || input.contains('*') {
            format!("SUCCESS: Expression {}", input)
        } else {
            let tokens: Vec<&str> = input.split_whitespace().collect();
            if tokens.len() == 4 && tokens[0] == "const" && tokens[2] == "=" {
                format!("SUCCESS: {}", input)
            } else {
                "ERROR".to_string()
            }
        }
    }
}
