// mkdbuild.rs - Universal build system that replaces cargo entirely
// Usage: mkdbuild file.rs --level=N

use std::env;
use std::fs;
use std::process::Command;

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() < 2 {
        println!("Usage: mkdbuild file.rs [--level=N]");
        return;
    }
    
    let source_file = &args[1];
    let level = extract_level(&args);
    
    println!("🔧 mkdbuild: Processing {} at level {}", source_file, level);
    
    // Read source file
    let content = fs::read_to_string(source_file).expect("Failed to read source");
    
    // Extract mkrust macros and generate code
    let generated = process_mkrust_macros(&content, level);
    
    // Write generated file
    let output_file = format!("generated_level_{}.rs", level);
    fs::write(&output_file, generated).expect("Failed to write output");
    
    // Compile directly with rustc (no cargo needed)
    let status = Command::new("rustc")
        .arg(&output_file)
        .arg("--cfg")
        .arg(&format!("level_{}", level))
        .status()
        .expect("Failed to run rustc");
    
    if status.success() {
        println!("✅ Built level {} compiler successfully", level);
        println!("🚀 Run: ./generated_level_{}", level);
    } else {
        println!("❌ Build failed");
    }
}

fn extract_level(args: &[String]) -> usize {
    for arg in args {
        if arg.starts_with("--level=") {
            return arg[8..].parse().unwrap_or(0);
        }
    }
    0
}

fn process_mkrust_macros(content: &str, target_level: usize) -> String {
    let mut output = String::new();
    
    // Add standard prelude
    output.push_str("// Generated by mkdbuild\n");
    output.push_str(&format!("// Target Level: {}\n\n", target_level));
    
    // Parse mkrust! macros and generate appropriate code
    let lines: Vec<&str> = content.lines().collect();
    let mut in_macro = false;
    let mut current_level = 0;
    let mut features = Vec::new();
    let mut functions = Vec::new();
    
    for line in lines {
        if line.trim().starts_with("mkrust!(") {
            in_macro = true;
            continue;
        }
        
        if in_macro && line.trim() == ");" {
            // Process collected macro data
            if current_level <= target_level {
                output.push_str(&generate_level_code(current_level, &features, &functions));
            }
            
            // Reset for next macro
            in_macro = false;
            features.clear();
            functions.clear();
            continue;
        }
        
        if in_macro {
            if line.trim().starts_with("level!(") {
                current_level = extract_number(line);
            } else if line.trim().starts_with("features!(") {
                features = extract_list(line);
            } else if line.trim().starts_with("functions!(") {
                functions = extract_list(line);
            }
        } else if !line.trim().starts_with("mkrust!(") && 
                  !line.trim().starts_with("//") && 
                  !line.trim().is_empty() {
            // Copy non-macro code
            output.push_str(line);
            output.push('\n');
        }
    }
    
    output
}

fn extract_number(line: &str) -> usize {
    line.chars()
        .filter(|c| c.is_ascii_digit())
        .collect::<String>()
        .parse()
        .unwrap_or(0)
}

fn extract_list(line: &str) -> Vec<String> {
    let start = line.find('(').unwrap_or(0) + 1;
    let end = line.find(')').unwrap_or(line.len());
    line[start..end]
        .split(',')
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .collect()
}

fn generate_level_code(level: usize, features: &[String], functions: &[String]) -> String {
    let mut code = String::new();
    
    code.push_str(&format!("// Level {} Implementation\n", level));
    code.push_str(&format!("#[cfg(level_{})]\n", level));
    code.push_str("mod level_impl {\n");
    
    for function in functions {
        code.push_str(&format!("    pub fn {}() {{\n", function));
        code.push_str(&format!("        println!(\"Executing {} (Level {})\");\n", function, level));
        code.push_str("    }\n");
    }
    
    code.push_str("}\n\n");
    code
}
