[features]
default = ["prime_2", "prime_13", "prime_11", "prime_3", "prime_5", "prime_19", "prime_7"]

prime_2 = []  # Algebraic component
prime_13 = []  # Memory component
prime_11 = []  # Presentation component
prime_3 = []  # Control component
prime_17 = []  # Concurrency component
prime_5 = []  # Relational component
prime_19 = []  # Collections component
prime_7 = []  # Recursive component
