[package]
name = "rust-eigenmatrix"
version = "0.1.0"
edition = "2021"

[workspace]

[[bin]]
name = "zombie-rustc"
path = "lib-zombie/src/bin/zombie_rustc.rs"

[[bin]]
name = "rust-eigenmatrix"
path = "rust_eigenmatrix.rs"

[[bin]]
name = "frequency-analysis"
path = "frequency_analysis.rs"

[[bin]]
name = "relationship-analysis"
path = "relationship_analysis.rs"

[[bin]]
name = "count-analysis"
path = "count_analysis.rs"

[dependencies]
nalgebra = "0.33"
serde_json = "1.0"
lib-zombie = { path = "lib-zombie" }
syn-analyzer = { path = "syn-analyzer" }
