[package]
name = "rustc_arena"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
smallvec = { path = "../../../mcp/monomcp/vendor/smallvec", features = ["union", "may_dangle"] }
# tidy-alphabetical-end
