[package]
name = "rustc_hashes"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
rustc-stable-hash = { path = "../../../mcp/monomcp/vendor/rustc-stable-hash" }
# tidy-alphabetical-end
